print ("Audio recognition software: version 12.34.4")
print ("Audio detected: Analysing")
print ("Analizing...")
print ("Analizing...")
print ("Analizing...")
print ("Analizing...")
print ("Analizing...")
print ("Done: Detected: Hapiness 82%, Sadness 12%, Other 6%")
print ("Process ended with status: 0")